name: Run Isabl CLI tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # If isabl_api is private, you may need to use a PAT (GH_PAT secret) instead of GITHUB_TOKEN
      # because GITHUB_TOKEN typically can't access private repos outside the current org

    steps:
    - name: Configure git and verify access
      run: | 
        # Check if token is set
        if [ -z "$TOKEN" ]; then
          echo "❌ ERROR: GH_TOKEN secret is not set"
          echo "Please add GH_TOKEN secret in repository settings"
          exit 1
        fi
        
        echo "Token length: ${#TOKEN} characters"
        echo "Token type: Classic Personal Access Token"
        
        # Configure git to use token for GitHub URLs
        # For classic PATs, use 'x-access-token' as username
        git config --global url."https://x-access-token:${TOKEN}@github.com/".insteadOf "https://github.com/"
        
        # Verify git config was set
        echo "Git config after setup:"
        git config --global --get-regexp url
        echo ""
        
        # Test access to the repository
        echo "Testing access to papaemmelab/isabl_api..."
        if git ls-remote https://github.com/papaemmelab/isabl_api.git HEAD > /dev/null 2>&1; then
          echo "✅ Successfully accessed papaemmelab/isabl_api"
          git ls-remote https://github.com/papaemmelab/isabl_api.git HEAD | head -1
        else
          echo "❌ ERROR: Cannot access papaemmelab/isabl_api repository"
          echo ""
          echo "For classic tokens, verify:"
          echo "  1. The token has 'repo' scope (required for private repos)"
          echo "  2. The token has access to papaemmelab organization"
          echo "  3. The token is not expired"
          echo "  4. The repository exists and spelling is correct"
          echo ""
          echo "Debug info:"
          echo "  Token length: ${#TOKEN}"
          echo "  Git config URL rewrite:"
          git config --global --get-regexp url || echo "  (no url rewrite found)"
          echo ""
          echo "Error details:"
          git ls-remote https://github.com/papaemmelab/isabl_api.git HEAD 2>&1 || true
          exit 1
        fi
      env:
        TOKEN: ${{ secrets.GH_PATH }}

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # Don't overwrite our git config for authentication

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Verify git config persists
      run: |
        echo "Verifying git config is still active:"
        git config --global --get-regexp url || echo "⚠️ No URL rewrite found - authentication may fail"
        echo ""
        echo "Re-testing repository access:"
        if git ls-remote https://github.com/papaemmelab/isabl_api.git HEAD > /dev/null 2>&1; then
          echo "✅ Repository still accessible"
        else
          echo "⚠️ Warning: Repository access check failed - tests may fail"
        fi

    - name: Run tests
      run: bash tests/test-with-compose.sh

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v4.2.0
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}