name: Run Isabl CLI tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # If isabl_api is private, you may need to use a PAT (GH_PAT secret) instead of GITHUB_TOKEN
      # because GITHUB_TOKEN typically can't access private repos outside the current org

    steps:
    - name: Configure git
      run: | 
        git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
        echo "Testing access to papaemmelab/isabl_api..."
        if git ls-remote https://github.com/papaemmelab/isabl_api.git HEAD > /dev/null 2>&1; then
          echo "✅ Successfully accessed papaemmelab/isabl_api"
          git ls-remote https://github.com/papaemmelab/isabl_api.git HEAD | head -1
        else
          echo "❌ ERROR: Cannot access papaemmelab/isabl_api repository"
          echo "This could mean:"
          echo "  1. The repository is private and the token doesn't have permission"
          echo "  2. The repository doesn't exist"
          echo "  3. The GH_TOKEN secret is not set or invalid"
          exit 1
        fi
      env:
        TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: bash tests/test-with-compose.sh

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v4.2.0
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}