name: Run Isabl CLI tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # If isabl_api is private, you may need to use a PAT (GH_PAT secret) instead of GITHUB_TOKEN
      # because GITHUB_TOKEN typically can't access private repos outside the current org

    steps:
    - name: Configure git authentication
      run: git config --global url."https://x-access-token:${TOKEN}@github.com/".insteadOf "https://github.com/"
      env:
        TOKEN: ${{ secrets.GH_PAT }}

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # Don't overwrite our git config for authentication

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: bash tests/test-with-compose.sh
      env:
        GH_PAT: ${{ secrets.GH_PAT }}

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v4.2.0
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}