name: Run Isabl CLI tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # If isabl_api is private, you may need to use a PAT (GH_PAT secret) instead of GITHUB_TOKEN
      # because GITHUB_TOKEN typically can't access private repos outside the current org

    steps:
    - name: Configure git and verify access
      run: | 
        # Check if token is set
        if [ -z "$TOKEN" ]; then
          echo "❌ ERROR: GH_TOKEN secret is not set"
          echo "Please add GH_TOKEN secret in repository settings"
          exit 1
        fi
        
        echo "Token length: ${#TOKEN} characters"
        echo "Token type: Fine-grained Personal Access Token"
        
        # Try multiple authentication methods for fine-grained tokens
        # Method 1: URL rewrite with x-access-token (works for both classic and fine-grained)
        git config --global url."https://x-access-token:${TOKEN}@github.com/".insteadOf "https://github.com/"
        
        # Method 2: Also set up credential helper as backup (for fine-grained tokens)
        git config --global credential.helper store
        
        # Verify git config was set
        echo "Git config after setup:"
        git config --global --get-regexp url
        echo ""
        
        # Test access to the repository
        echo "Testing access to papaemmelab/isabl_api..."
        echo "Attempt 1: Using URL rewrite..."
        
        if git ls-remote https://github.com/papaemmelab/isabl_api.git HEAD > /dev/null 2>&1; then
          echo "✅ Successfully accessed papaemmelab/isabl_api"
          git ls-remote https://github.com/papaemmelab/isabl_api.git HEAD | head -1
        else
          echo "Attempt 1 failed. Trying with direct token in URL..."
          # Method 2: Try direct URL with token embedded
          if git ls-remote "https://x-access-token:${TOKEN}@github.com/papaemmelab/isabl_api.git" HEAD > /dev/null 2>&1; then
            echo "✅ Successfully accessed with direct token URL"
            # Update git config to use this method
            git config --global --unset url."https://x-access-token:${TOKEN}@github.com/".insteadOf
            git config --global url."https://x-access-token:${TOKEN}@github.com/".insteadOf "https://github.com/"
            git ls-remote "https://x-access-token:${TOKEN}@github.com/papaemmelab/isabl_api.git" HEAD | head -1
          else
            echo "❌ ERROR: Cannot access papaemmelab/isabl_api repository"
            echo ""
            echo "For fine-grained tokens, verify:"
            echo "  1. The token has 'Repository access' permissions"
            echo "  2. The token specifically includes 'papaemmelab/isabl_api' repository"
            echo "  3. The token has 'Contents: Read' permission"
            echo "  4. The token is not expired"
            echo ""
            echo "Debug info:"
            echo "  Token length: ${#TOKEN}"
            echo "  Git config URL rewrite:"
            git config --global --get-regexp url || echo "  (no url rewrite found)"
            echo ""
            echo "Attempting to show error:"
            git ls-remote https://github.com/papaemmelab/isabl_api.git HEAD 2>&1 || true
            echo ""
            git ls-remote "https://x-access-token:${TOKEN}@github.com/papaemmelab/isabl_api.git" HEAD 2>&1 || true
            exit 1
          fi
        fi
      env:
        TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # Don't overwrite our git config for authentication

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Verify git config persists
      run: |
        echo "Verifying git config is still active:"
        git config --global --get-regexp url || echo "⚠️ No URL rewrite found - authentication may fail"
        echo ""
        echo "Re-testing repository access:"
        if git ls-remote https://github.com/papaemmelab/isabl_api.git HEAD > /dev/null 2>&1; then
          echo "✅ Repository still accessible"
        else
          echo "⚠️ Warning: Repository access check failed - tests may fail"
        fi

    - name: Run tests
      run: bash tests/test-with-compose.sh

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v4.2.0
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}